### ISSUE TITLE
Design clarification on publishing a public article

### ISSUE THREAD

**Issue by pavgill0805** [intercom/Intercom-OpenAPI#148]
![Image](https://github.com/intercom/Intercom-OpenAPI/assets/167209726/8f57aa81-1634-4423-9daa-b0ec2f5028c4)

Creation steps: 
1) Create an article 
2) Go to publish it 
3) Between the two radio buttons choose the second (unlisted public article) 
4) Should the first then be made inactive - otherwise seems like a confusing journey 

@anapsampaio + @alinaberndt

**Comment by Eclairemoy** [comment]
hey @pavgill0805 i think you meant to open this issue in this repo: https://github.com/intercom/intercom/issues

this one is for the OpenAPI spec
