### ISSUE TITLE
The mixed help centre status seems confusing

### ISSUE THREAD

**Issue by pavgill0805** [intercom/Intercom-OpenAPI#149]
![Image](https://github.com/intercom/Intercom-OpenAPI/assets/167209726/ec2ce095-cf31-4498-bdb9-20286ae24892)

The mixed status for the product columns (AI Agent & Copilot Agent) and for the Help Centre status seem to be confusing and not clear what this means for each of the columns it's in. 

FYI: @anapsampaio 
CC: @alinaberndt

**Comment by Eclairemoy** [comment]
hey @pavgill0805 i think you meant to open this issue in this repo: https://github.com/intercom/intercom/issues

this one is for the OpenAPI spec
