### ISSUE TITLE
The error messaging when changing enable / disable misleading

### ISSUE THREAD

**Issue by pavgill0805** [intercom/Intercom-OpenAPI#150]
![Image](https://github.com/intercom/Intercom-OpenAPI/assets/167209726/0da112a5-e8a4-4814-9058-dfb114f2afdd)

For this example which is an internal article, AI Agent shouldn't be allowed to be enabled, however although from a technical standpoint we're not allowing this, the error message doesn't make this entirely clear 

FYI: @anapsampaio / @alinaberndt

**Comment by Eclairemoy** [comment]
hey @pavgill0805 i think you meant to open this issue in this repo: https://github.com/intercom/intercom/issues

this one is for the OpenAPI spec
