### ISSUE TITLE
[Schema Inaccuracy] In SearchContacts, `pagination.per_page` is not defined.

### ISSUE THREAD

**Issue by yacinehmito** [intercom/Intercom-OpenAPI#98]
# Schema Inaccuracy

There is an inconsistency between the schema of _SearchContacts_ and what is documented in the API docs:

[API docs documentation states that the `pagination.per_page` is to be provided in the request body to specify the number of items to return](https://developers.intercom.com/building-apps/docs/pagination-sorting-search).

However, both v2.9 and Unstable do not include this property, and instead define `pagination.page`.
See the following lines (for v2.9):
- https://github.com/intercom/Intercom-OpenAPI/blob/2498a89ea9d3bceb52b7ba345357df00351f607a/descriptions/2.9/api.intercom.io.yaml#L14873-L14885
- https://github.com/intercom/Intercom-OpenAPI/blob/2498a89ea9d3bceb52b7ba345357df00351f607a/descriptions/2.9/api.intercom.io.yaml#L15143-L15153

I tested real API calls with both `pagination.per_page` and `pagination.page` and the former is the one that works as expected; the latter has no effect.

⚠️ The component `starting_after_paging`, which is relied on for `pagination` of _SearchContacts_ ' request body, also appear here:
https://github.com/intercom/Intercom-OpenAPI/blob/2498a89ea9d3bceb52b7ba345357df00351f607a/descriptions/2.9/api.intercom.io.yaml#L13547

This reference expects `pagination.page` and not `pagination.per_page` as it is a reference of the next page.

The two must be decoupled.

## Expected

We would expect to have `pagination.per_page` instead of `pagination.page` in the OpenAPI spec.

## Reproduction Steps

N/A.

**Comment by yacinehmito** [comment]
Additionally: it would be great to document in the schema the maximum value for `per_page`. I found out that it is 150.

**Comment by Eclairemoy** [comment]
this has now been fixed https://github.com/intercom/Intercom-OpenAPI/blob/d9b831335d12c5fa4cee6c3936ff41abb85f8c07/descriptions/2.9/api.intercom.io.yaml#L15026
